name: Conventions Validation
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Validate ports and env conventions
        run: |
          node scripts/validate-conventions.mjs
